-- Oracle compatibility function pack for OpenTenBase ora-mode
-- Fixes: DATE/TIMESTAMP +/- NUMERIC, ADD_MONTHS, MONTHS_BETWEEN, TRUNC, LAST_DAY
-- Updated: added TIMESTAMP/TIMESTAMPTZ operators + TRUNC format translation

-- ========== DATE +/- NUMERIC ==========
-- Caveat: PG DATE has no time component, fractional days are truncated.
-- For sub-day precision, use TIMESTAMP +/- NUMERIC instead.
DROP FUNCTION IF EXISTS date_minus_numeric(DATE, NUMERIC) CASCADE;
CREATE OR REPLACE FUNCTION date_minus_numeric(d DATE, n NUMERIC)
RETURNS DATE AS 'SELECT d - CAST(n AS INTEGER)'
LANGUAGE SQL IMMUTABLE STRICT;
DROP OPERATOR IF EXISTS - (DATE, NUMERIC);
CREATE OPERATOR - (LEFTARG = DATE, RIGHTARG = NUMERIC, PROCEDURE = date_minus_numeric);

DROP FUNCTION IF EXISTS date_plus_numeric(DATE, NUMERIC) CASCADE;
CREATE OR REPLACE FUNCTION date_plus_numeric(d DATE, n NUMERIC)
RETURNS DATE AS 'SELECT d + CAST(n AS INTEGER)'
LANGUAGE SQL IMMUTABLE STRICT;
DROP OPERATOR IF EXISTS + (DATE, NUMERIC);
CREATE OPERATOR + (LEFTARG = DATE, RIGHTARG = NUMERIC, PROCEDURE = date_plus_numeric);

-- ========== TIMESTAMP +/- NUMERIC ==========
-- v2: removed CAST(n AS INTEGER) to preserve fractional days
DROP FUNCTION IF EXISTS ts_minus_numeric(TIMESTAMP, NUMERIC) CASCADE;
CREATE OR REPLACE FUNCTION ts_minus_numeric(ts TIMESTAMP, n NUMERIC)
RETURNS TIMESTAMP AS 'SELECT ts - n * INTERVAL ''1 day'''
LANGUAGE SQL IMMUTABLE STRICT;
DROP OPERATOR IF EXISTS - (TIMESTAMP, NUMERIC);
CREATE OPERATOR - (LEFTARG = TIMESTAMP, RIGHTARG = NUMERIC, PROCEDURE = ts_minus_numeric);

DROP FUNCTION IF EXISTS ts_plus_numeric(TIMESTAMP, NUMERIC) CASCADE;
CREATE OR REPLACE FUNCTION ts_plus_numeric(ts TIMESTAMP, n NUMERIC)
RETURNS TIMESTAMP AS 'SELECT ts + n * INTERVAL ''1 day'''
LANGUAGE SQL IMMUTABLE STRICT;
DROP OPERATOR IF EXISTS + (TIMESTAMP, NUMERIC);
CREATE OPERATOR + (LEFTARG = TIMESTAMP, RIGHTARG = NUMERIC, PROCEDURE = ts_plus_numeric);

-- ========== TIMESTAMPTZ +/- NUMERIC ==========
-- v2: removed CAST(n AS INTEGER) to preserve fractional days
DROP FUNCTION IF EXISTS tstz_minus_numeric(TIMESTAMPTZ, NUMERIC) CASCADE;
CREATE OR REPLACE FUNCTION tstz_minus_numeric(ts TIMESTAMPTZ, n NUMERIC)
RETURNS TIMESTAMPTZ AS 'SELECT ts - n * INTERVAL ''1 day'''
LANGUAGE SQL IMMUTABLE STRICT;
DROP OPERATOR IF EXISTS - (TIMESTAMPTZ, NUMERIC);
CREATE OPERATOR - (LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC, PROCEDURE = tstz_minus_numeric);

DROP FUNCTION IF EXISTS tstz_plus_numeric(TIMESTAMPTZ, NUMERIC) CASCADE;
CREATE OR REPLACE FUNCTION tstz_plus_numeric(ts TIMESTAMPTZ, n NUMERIC)
RETURNS TIMESTAMPTZ AS 'SELECT ts + n * INTERVAL ''1 day'''
LANGUAGE SQL IMMUTABLE STRICT;
DROP OPERATOR IF EXISTS + (TIMESTAMPTZ, NUMERIC);
CREATE OPERATOR + (LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC, PROCEDURE = tstz_plus_numeric);

-- ========== ADD_MONTHS ==========
CREATE OR REPLACE FUNCTION add_months(d DATE, n INTEGER)
RETURNS DATE AS 'SELECT (d + INTERVAL ''1 month'' * n)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION add_months(d TIMESTAMP, n INTEGER)
RETURNS DATE AS 'SELECT (d + INTERVAL ''1 month'' * n)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

-- ========== MONTHS_BETWEEN ==========
-- Oracle formula: (year*12+month diff) + (day diff)/31
-- v2: fixed missing fractional day part (was returning integer only)
DROP FUNCTION IF EXISTS months_between(DATE, DATE) CASCADE;
DROP FUNCTION IF EXISTS months_between(TIMESTAMP, TIMESTAMP) CASCADE;

CREATE OR REPLACE FUNCTION months_between(d1 DATE, d2 DATE)
RETURNS NUMERIC AS $$
DECLARE
    total_months1 int;
    total_months2 int;
    day_diff int;
    month_diff numeric;
BEGIN
    total_months1 := EXTRACT(YEAR FROM d1)::int * 12 + EXTRACT(MONTH FROM d1)::int;
    total_months2 := EXTRACT(YEAR FROM d2)::int * 12 + EXTRACT(MONTH FROM d2)::int;
    day_diff := EXTRACT(DAY FROM d1)::int - EXTRACT(DAY FROM d2)::int;
    month_diff := total_months1 - total_months2;
    RETURN month_diff + (day_diff::numeric / 31);
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION months_between(d1 TIMESTAMP, d2 TIMESTAMP)
RETURNS NUMERIC AS $$
DECLARE
    total_months1 int;
    total_months2 int;
    day_diff int;
    month_diff numeric;
BEGIN
    total_months1 := EXTRACT(YEAR FROM d1)::int * 12 + EXTRACT(MONTH FROM d1)::int;
    total_months2 := EXTRACT(YEAR FROM d2)::int * 12 + EXTRACT(MONTH FROM d2)::int;
    day_diff := EXTRACT(DAY FROM d1)::int - EXTRACT(DAY FROM d2)::int;
    month_diff := total_months1 - total_months2;
    RETURN month_diff + (day_diff::numeric / 31);
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

-- ========== TRUNC for DATE/TIMESTAMP (with Oracle format translation) ==========
DROP FUNCTION IF EXISTS trunc(DATE);
DROP FUNCTION IF EXISTS trunc(DATE, VARCHAR2);
DROP FUNCTION IF EXISTS trunc(TIMESTAMP);
DROP FUNCTION IF EXISTS trunc(TIMESTAMP, VARCHAR2);

-- Helper: translate Oracle fmt codes to PostgreSQL (DD->day, MM->month, YYYY->year, etc.)
CREATE OR REPLACE FUNCTION ora_fmt_to_pg(fmt VARCHAR2) RETURNS VARCHAR2 AS $$
SELECT CASE UPPER(fmt)
  WHEN 'DD' THEN 'day'
  WHEN 'D' THEN 'day'
  WHEN 'MM' THEN 'month'
  WHEN 'MON' THEN 'month'
  WHEN 'MONTH' THEN 'month'
  WHEN 'YY' THEN 'year'
  WHEN 'YYYY' THEN 'year'
  WHEN 'YEAR' THEN 'year'
  WHEN 'HH' THEN 'hour'
  WHEN 'HH12' THEN 'hour'
  WHEN 'HH24' THEN 'hour'
  WHEN 'MI' THEN 'minute'
  WHEN 'Q' THEN 'quarter'
  WHEN 'W' THEN 'week'
  WHEN 'IW' THEN 'week'
  ELSE fmt
END
$$ LANGUAGE SQL IMMUTABLE STRICT;

-- TRUNC(date) - strip time
CREATE OR REPLACE FUNCTION trunc(d DATE) RETURNS DATE AS 'SELECT d'
LANGUAGE SQL IMMUTABLE STRICT;

-- TRUNC(date, fmt)
CREATE OR REPLACE FUNCTION trunc(d DATE, fmt VARCHAR2)
RETURNS DATE AS 'SELECT DATE_TRUNC(ora_fmt_to_pg(fmt), d)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

-- TRUNC(timestamp)
CREATE OR REPLACE FUNCTION trunc(d TIMESTAMP) RETURNS DATE AS 'SELECT d::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

-- TRUNC(timestamp, fmt)
CREATE OR REPLACE FUNCTION trunc(d TIMESTAMP, fmt VARCHAR2)
RETURNS DATE AS 'SELECT DATE_TRUNC(ora_fmt_to_pg(fmt), d)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

-- ========== LAST_DAY ==========
CREATE OR REPLACE FUNCTION last_day(d DATE)
RETURNS DATE AS 'SELECT (DATE_TRUNC(''month'', d) + INTERVAL ''1 month'' - INTERVAL ''1 day'')::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION last_day(d TIMESTAMP)
RETURNS DATE AS 'SELECT (DATE_TRUNC(''month'', d) + INTERVAL ''1 month'' - INTERVAL ''1 day'')::DATE'
LANGUAGE SQL IMMUTABLE STRICT;
