-- Oracle compatibility function pack for OpenTenBase ora-mode
-- Fixes: DATE +/- NUMERIC, ADD_MONTHS, MONTHS_BETWEEN, TRUNC, LAST_DAY

-- 1. DATE - NUMERIC operator
CREATE OR REPLACE FUNCTION date_minus_numeric(d DATE, n NUMERIC)
RETURNS DATE AS 'SELECT d - CAST(n AS INTEGER)'
LANGUAGE SQL IMMUTABLE STRICT;

DROP OPERATOR IF EXISTS - (DATE, NUMERIC);
CREATE OPERATOR - (LEFTARG = DATE, RIGHTARG = NUMERIC, PROCEDURE = date_minus_numeric);

-- 2. DATE + NUMERIC operator
CREATE OR REPLACE FUNCTION date_plus_numeric(d DATE, n NUMERIC)
RETURNS DATE AS 'SELECT d + CAST(n AS INTEGER)'
LANGUAGE SQL IMMUTABLE STRICT;

DROP OPERATOR IF EXISTS + (DATE, NUMERIC);
CREATE OPERATOR + (LEFTARG = DATE, RIGHTARG = NUMERIC, PROCEDURE = date_plus_numeric);

-- 3. ADD_MONTHS
CREATE OR REPLACE FUNCTION add_months(d DATE, n INTEGER)
RETURNS DATE AS 'SELECT (d + INTERVAL ''1 month'' * n)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION add_months(d TIMESTAMP, n INTEGER)
RETURNS DATE AS 'SELECT (d + INTERVAL ''1 month'' * n)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

-- 4. MONTHS_BETWEEN
DROP FUNCTION IF EXISTS months_between(DATE, DATE);
DROP FUNCTION IF EXISTS months_between(TIMESTAMP, TIMESTAMP);

CREATE OR REPLACE FUNCTION months_between(d1 DATE, d2 DATE)
RETURNS NUMERIC AS 'SELECT CAST(EXTRACT(YEAR FROM AGE(d1, d2)) * 12 + EXTRACT(MONTH FROM AGE(d1, d2)) AS NUMERIC)'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION months_between(d1 TIMESTAMP, d2 TIMESTAMP)
RETURNS NUMERIC AS 'SELECT CAST(EXTRACT(YEAR FROM AGE(d1, d2)) * 12 + EXTRACT(MONTH FROM AGE(d1, d2)) AS NUMERIC)'
LANGUAGE SQL IMMUTABLE STRICT;

-- 5. TRUNC for DATE
CREATE OR REPLACE FUNCTION trunc(d DATE) RETURNS DATE AS 'SELECT d'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION trunc(d DATE, fmt VARCHAR2)
RETURNS DATE AS 'SELECT DATE_TRUNC(fmt, d)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION trunc(d TIMESTAMP) RETURNS DATE AS 'SELECT d::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION trunc(d TIMESTAMP, fmt VARCHAR2)
RETURNS DATE AS 'SELECT DATE_TRUNC(fmt, d)::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

-- 6. LAST_DAY
CREATE OR REPLACE FUNCTION last_day(d DATE)
RETURNS DATE AS 'SELECT (DATE_TRUNC(''month'', d) + INTERVAL ''1 month'' - INTERVAL ''1 day'')::DATE'
LANGUAGE SQL IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION last_day(d TIMESTAMP)
RETURNS DATE AS 'SELECT (DATE_TRUNC(''month'', d) + INTERVAL ''1 month'' - INTERVAL ''1 day'')::DATE'
LANGUAGE SQL IMMUTABLE STRICT;
